name: bolt_state_notifier
description: Bolt Notifier .
version: 0.1.0
topics: [state-management, state-notifier, bolt, event-driven]
homepage: "https://github.com/s1r1m1r1/bolt"

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  bolt_base: ^0.1.0
  state_notifier: ^1.0.0

resolution: workspace
